##################################################
## Map Key:
##
## 1 - player 1
## 2 - player 2
## Z - zombie
## U - zombie spawn
## S - sand
## V - vegetation
## T - topsoil
## M - mud
## B - bedrock
## J - diamond
## E - emerald
## G - gold
## I - iron
## R - ruby
## D - dynamite
## N - tnt
## A - atombomb
## C - cloud
## W - water
## L - lava
## ^ - bouncepad
## P - powerup
##################################################

class CampaignMaps:
    map1 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "                                                ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                         U",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map2 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "              ^                                 ",
            "           BBBBBBBB                       B     ",
            "                                          B  U  ",
            "                                       BBBBBBBBB",
            "P                                               ",
            "VV^  1                                         U",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map3 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                 ^              ",
            "    ^                 ^                         ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                            ^  ",
            "                  ^         CC                  ",
            "                         CCCCCCC   ^            ",
            "   ^                                 U          ",
            "              N  U                BBBBB         ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                             ^                  ",
            "P                                               ",
            "VV^  1                                        UU",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map4 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                   UUUUUUU",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map5 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                   UUUUUUU",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map6 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                   UUUUUUU",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map7 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                   UUUUUUU",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map8 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                   UUUUUUU",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]

############################################################################################################################
############################################################################################################################
############################################################################################################################
############################################################################################################################
############################################################################################################################

class MultiplayerMaps:
    map1 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                 ^                        ^     ",
            "                                                ",
            "                                        C       ",
            "           ^                   ^      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                        ^       ",
            "       ^   TWWWWWWT                             ",
            "           MMMMMMMM           TWWWWT            ",
            "                              MMMMMM            ",
            "                                                ",
            "                                                ",
            "VV^  1       N                            2  ^VV",
            "TTTTTTTSWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMMSSSSWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map2 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                    2     ",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map3 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                    2     ",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map4 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                    2     ",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map5 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                    2     ",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map6 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                    2     ",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map7 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                    2     ",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
    map8 = ["                                                ",
            "                                                ",
            "                                                ",
            "                                        CCC     ",
            "                                       CCCCCC   ",
            "          CCCCCCCC                              ",
            "      CCCCCCCCCCCCCCCC                          ",
            "  CCCCCCCCCCCCCCCCCCCCCCCCCCCCC                 ",
            "                                                ",
            "                                                ",
            "                                        C       ",
            "                                      CCCCC     ",
            "            CC C                    CCCCCCCCC   ",
            "          CCCCCCC                               ",
            "                            CC                  ",
            "                         CCCCCCC                ",
            "                                                ",
            "            D N A                               ",
            "           BBBBBBBB                             ",
            "                                                ",
            "                                                ",
            "P                                               ",
            "VV^  1                                    2     ",
            "TTTSWWWWWWWWWWSTBLLLLLLLLLLLBTTTTTTTTTTTTTTTTTTT",
            "MMMSWWWWWWWWWWSMBLLLLLLLLLLLBMMMMMMMMMMMMMMMMMMM",
            "MMMSSWWWWWWWWSSMBBLLLLLLLLLBBMMMMMMMMMMMMMMMMMMM",
            "MMMMSSSSSSSSSSMMMBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMBBBBBBBMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMM",
            "BBMMMBBBBBBBBBBBBBBBBBBMMBBBBBBBBEEEBBMMMMJJJJJJ",
            "BBBBBBBBBBBBBGGGGBBBBRBBRRBBBBBBEEEEEBBBJJJLLLLL",
            "BBBBIIIIIIIBBBGGGGBBBRRRRRBBBBBBBEEBBBBBJLLLLLLL"]
